In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
vaccinedf = pd.read_csv("/workspace/COVIDResearch/COVIDVaccinationsUSCounty.csv", encoding='latin1')

/tmp/ipykernel_2146/1221815491.py:1: DtypeWarning: Columns (8,18,20,28,30,32,34,36,38,67,68,71,72,74,76,78) have mixed types. Specify dtype option on import or set low_memory=False.
  vaccinedf = pd.read_csv("/workspace/COVIDResearch/COVIDVaccinationsUSCounty.csv", encoding='latin1')

In [4]:
vaccinedf.head()

,Date,FIPS,MMWR_week,Recip_County,Recip_State,Completeness_pct,Administered_Dose1_Recip,Administered_Dose1_Pop_Pct,Administered_Dose1_Recip_5Plus,Administered_Dose1_Recip_5PlusPop_Pct,...,Census2019_18PlusPop,Census2019_65PlusPop,Bivalent_Booster_5Plus,Bivalent_Booster_5Plus_Pop_Pct,Bivalent_Booster_12Plus,Bivalent_Booster_12Plus_Pop_Pct,Bivalent_Booster_18Plus,Bivalent_Booster_18Plus_Pop_Pct,Bivalent_Booster_65Plus,Bivalent_Booster_65Plus_Pop_Pct
0,05/10/2023,51820,19,Waynesboro city,VA,78.1,"11,432",50.5,"11,388",54.2,...,"17,265","4,031",757,3.6,752,4.0,731,4.2,386,9.6
1,05/10/2023,51171,19,Shenandoah County,VA,78.1,"25,330",58.1,"25,275",61.3,...,"34,452","9,690","4,980",12.1,"4,955",13.2,"4,891",14.2,"3,116",32.2
2,05/10/2023,51157,19,Rappahannock County,VA,78.1,"5,026",68.2,"5,003",70.6,...,"6,174","2,053",962,13.6,950,14.4,934,15.1,603,29.4
3,05/10/2023,51183,19,Sussex County,VA,78.1,"4,692",42.0,"4,691",43.8,...,"9,462","2,070",656,6.1,656,6.5,656,6.9,129,6.2
4,05/10/2023,51700,19,Newport News city,VA,78.1,"111,702",62.3,"111,200",66.9,...,"137,743","23,892","14,101",8.5,"13,904",9.3,"13,533",9.8,"6,320",26.5

In [2]:
nhgis5 = pd.read_csv("/workspace/COVIDResearch/nhgis0003_ds254_20215_county.csv", encoding='latin1')
nhgis2019 = pd.read_csv("/workspace/COVIDResearch/nhgis0003_ds243_2019_county.csv", encoding='latin1')
nhgis2021 = pd.read_csv("/workspace/COVIDResearch/nhgis0003_ds253_2021_county.csv", encoding='latin1')

In [3]:
nhgis5

,GISJOIN,YEAR,STUSAB,REGIONA,DIVISIONA,STATE,STATEA,COUNTY,COUNTYA,COUSUBA,...,AOP8M019,AOP8M020,AOP8M021,AOP8M022,AOP8M023,AOP8M024,AOP8M025,AOQIM001,AOQJM001,AORGM001
0,G5100010,2017-2021,VA,NaN,NaN,Virginia,51,Accomack County,1,NaN,...,327,436,334,418,308,98,109,5803,64566342,4109
1,G5100030,2017-2021,VA,NaN,NaN,Virginia,51,Albemarle County,3,NaN,...,422,754,444,1103,837,487,440,3359,213308039,5824
2,G5100050,2017-2021,VA,NaN,NaN,Virginia,51,Alleghany County,5,NaN,...,211,241,213,187,131,56,82,5345,31738951,5202
3,G5100070,2017-2021,VA,NaN,NaN,Virginia,51,Amelia County,7,NaN,...,161,354,234,244,158,104,37,10638,48944215,12345
4,G5100090,2017-2021,VA,NaN,NaN,Virginia,51,Amherst County,9,NaN,...,250,372,276,347,301,55,155,3561,74246632,5630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,G5108000,2017-2021,VA,NaN,NaN,Virginia,51,Suffolk city,800,NaN,...,445,726,612,691,536,192,195,3471,196076469,4571
129,G5108100,2017-2021,VA,NaN,NaN,Virginia,51,Virginia Beach city,810,NaN,...,1372,1803,1688,1990,1270,640,631,1205,344010152,1807
130,G5108200,2017-2021,VA,NaN,NaN,Virginia,51,Waynesboro city,820,NaN,...,308,278,294,350,298,127,111,6024,70040175,9413
131,G5108300,2017-2021,VA,NaN,NaN,Virginia,51,Williamsburg city,830,NaN,...,153,172,191,279,220,108,129,7470,60563980,10653
132,G5108400,2017-2021,VA,NaN,NaN,Virginia,51,Winchester city,840,NaN,...,250,430,286,397,301,136,106,4618,45686813,10130

In [ ]:
pip install requests beautifulsoup4 vaderSentiment

# in VS Code — scripts/scrape_cdc.py
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

BASE = "https://newsroom.cdc.gov/pressreleases"